# Generated by Django 2.1 on 2019-02-04 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('componants', '0003_auto_20190204_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='driversalary',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_salary', to='componants.Driver'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='holidays',
            field=models.CharField(choices=[('fri-sat', 'Friday and Satrday'), ('thu-fri', 'Friday and Thursday')], max_length=7),
        ),
    ]
