# Generated by Django 2.1 on 2019-02-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('componants', '0004_auto_20190204_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driversalary',
        ),
    ]
